In [4]:
import pandas as pd
import numpy as mp
from sklearn import linear_model


In [3]:
df=pd.read_csv("bedrooms.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

fill missing values


In [6]:
import math
medianv=math.floor(df.bedrooms.median())
medianv

3

In [9]:
df.bedrooms=df.bedrooms.fillna(medianv)

In [10]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [11]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)


LinearRegression()

In [12]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [13]:
reg.intercept_

np.float64(383725.00000000006)

In [14]:
reg.predict([[3000,3,40]])

/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

y=mx+c
y=m1*x1+m2*x2+m3*x3+c
price=m1*area+m2*bedroom+m3*age+c

In [15]:
137.25*3000+-26025.*3+-6825.*40+383725.00000000006

444400.00000000006

In [16]:
reg.predict([[2500,4,5]])

/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([588625.])

using multilinear regression for a data set

In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n

In [ ]:
df1=pd.read_csv("interview.csv")
df1

In [ ]:
d.experience = d.experience.fillna("zero")
d

In [ ]:
d.experience = d.experience.apply(w2n.word_to_num)
d

In [ ]:
import math
median_test_score = math.floor(d['test_score'].mean())
median_test_score

In [ ]:
d['test_score'] = d['test_score'].fillna(median_test_score)
d

fit the model


In [ ]:
reg=linear_model.LinearRegression()
reg.fit(df[['experience','test_score','interview_score']],df.salary)

In [ ]:

reg.predict([[2,9,6]])